version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v19-branch
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v18-branch
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v17-branch
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v16-branch
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v15-branch
