version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v12-branch
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v11-branch
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v10-branch
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: "direct"
  versioning-strategy: "increase"
  target-branch: v9-branch
